eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:1000/eureka/

server:
  port: 2000

spring:
  application:
    name: mall-gateway-zuul

zuul:
  routes:
    #/order 开头匹配到mall-order-eureka
    order:
      path: /order/**
      serviceId: mall-order-eureka
    #/good/ 开头匹配到mall-good-eureka
    good:
      path: /good/**
      serviceId: mall-good-eureka
    #匹配/github/直接重定向到https://github.com/
    github:
      path: /github/**
      url: https://github.com/
